volumes:
  node_modules:
services:
  my-nuxt-app:
    build:
      context: ../..
      dockerfile: docker/local/my-nuxt-app/Dockerfile
    ports:
      - "3000:3000"
      - "24678:24678" # for Vite
      - "9229:9229" # for Nuxt.js devtools
    volumes:
      - ../..:/src:delegated
      - node_modules:/src/node_modules
    env_file:
      - my-nuxt-app/.env
